# ====================================================================================================
# knime2py — KNIME → Python workbook
# Workflow: INZ_visa_decisions_combined__g01
# Source:   /work/INZ_visa_decisions_combined/workflow.knime
#
# This file was generated by the open-source knime2py project (KNIME → Python codegen).
# GitHub: https://github.com/vitalii-kaplan/knime2py
#
# Notes:
# • The code below is a linear translation of KNIME nodes into Python sections.
# • A lightweight `context` dict is available for debugging/inspection of intermediate tables.
#
# Export coverage:
# • All nodes successfully exported.
# ====================================================================================================

from matplotlib.colors import LinearSegmentedColormap
from pathlib import Path
from scipy import stats as _sstats
import csv
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import re as _re
import tempfile

# Simple shared context to pass tabular data between sections (for debugging)
context = {}  # e.g., {'<node_id>:<port>': df}

################################################################################################################################################################
## CSV Reader # `1545`
# Node state: `EXECUTED`
# Output: [Port 1] 1545:1 to 1547 Joiner #1547
# comments: WHO.csv
# https://hub.knime.com/knime/extensions/org.knime.features.base/latest/org.knime.base.node.io.filehandling.csv.reader.CSVTableReaderNodeFactory
csv_path = Path(r"data/original/who_countries_with_references.csv")
# Note: escapechar equals quotechar; omitting escapechar and relying on double-quoted escapes.
df = pd.read_csv(csv_path, sep=',', quotechar='"', header=0, encoding='UTF-8', na_values=['', ' '], keep_default_na=True, skipinitialspace=True)
_pd_dtypes = {'Country': 'string', 'WHO_Region': 'string', 'WHO_Official_Name': 'string', 'WHO_GEO_M49': 'Int64', 'WHO_Life_Expectancy_at_Birth_years': 'Float64', 'WHO_Life_Expectancy_Year': 'Int64', 'WHO_Healthy_Life_Expectancy_at_Birth_years': 'Float64', 'WHO_Healthy_Life_Expectancy_Year': 'Int64', 'WHO_Under5_Mortality_per_1000_live_births': 'Float64', 'WHO_Under5_Mortality_Year': 'Int64', 'WHO_Maternal_Mortality_per_100000_live_births': 'Float64', 'WHO_Maternal_Mortality_Year': 'Int64', 'WHO_DTP3_Immunization_Coverage_pct': 'Int64', 'WHO_DTP3_Year': 'Int64', 'WHO_Physician_Density_per_10000_population': 'Float64', 'WHO_Physician_Density_Year': 'Int64', 'WHO_Source_URLs': 'string'}
for _col, _dt in _pd_dtypes.items():
    if _col not in df.columns:
        continue
    try:
        if _dt in ('Int64', 'Float64'):
            df[_col] = pd.to_numeric(df[_col], errors='coerce').astype(_dt)
        else:
            df[_col] = df[_col].astype(_dt)
    except Exception:  # leave column as-is on failure
        pass
context['1545:1'] = df

################################################################################################################################################################
## CSV Reader # `1546`
# Node state: `EXECUTED`
# Output: [Port 1] 1546:1 to 1551 Joiner #1551
# comments: WB.csv
# https://hub.knime.com/knime/extensions/org.knime.features.base/latest/org.knime.base.node.io.filehandling.csv.reader.CSVTableReaderNodeFactory
csv_path = Path(r"data/original/wb_countries_with_references.csv")
# Note: escapechar equals quotechar; omitting escapechar and relying on double-quoted escapes.
df = pd.read_csv(csv_path, sep=',', quotechar='"', header=0, encoding='UTF-8', na_values=['', ' '], keep_default_na=True, skipinitialspace=True)
_pd_dtypes = {'Country': 'string', 'WB_Code': 'string', 'WB_Official_Name': 'string', 'WB_FY2026_Region': 'string', 'WB_FY2026_Income_Group': 'string', 'WB_FY2026_Lending_Category': 'string', 'Population_Total': 'Int64', 'Population_Total_Year': 'Int64', 'GDP_per_capita_current_USD': 'Float64', 'GDP_per_capita_current_USD_Year': 'Int64', 'GNI_per_capita_Atlas_current_USD_Year': 'Int64', 'Life_expectancy_at_birth_years': 'Float64', 'Life_expectancy_at_birth_years_Year': 'Int64', 'Internet_users_pct_population': 'Float64', 'Internet_users_pct_population_Year': 'Int64', 'Urban_population_pct': 'Float64', 'Urban_population_pct_Year': 'Int64', 'GNI_per_capita_Atlas_current_USD': 'Int64', 'Reference': 'string'}
for _col, _dt in _pd_dtypes.items():
    if _col not in df.columns:
        continue
    try:
        if _dt in ('Int64', 'Float64'):
            df[_col] = pd.to_numeric(df[_col], errors='coerce').astype(_dt)
        else:
            df[_col] = df[_col].astype(_dt)
    except Exception:  # leave column as-is on failure
        pass
context['1546:1'] = df

################################################################################################################################################################
## CSV Reader # `1587`
# Node state: `EXECUTED`
# Output: [Port 1] 1587:1 to 1547 Joiner #1547; [Port 1] 1587:1 to 1551 Joiner #1551; [Port 1] 1587:1 to 1572 Scatter Plot #1572; [Port 1] 1587:1 to 1592 Joiner #1592
# comments: INZ.csv
# https://hub.knime.com/knime/extensions/org.knime.features.base/latest/org.knime.base.node.io.filehandling.csv.reader.CSVTableReaderNodeFactory
csv_path = Path(r"data/prepared/inz_student_visa_decisions_2022-2025.csv")
# Note: escapechar equals quotechar; omitting escapechar and relying on double-quoted escapes.
df = pd.read_csv(csv_path, sep=',', quotechar='"', header=0, encoding='UTF-8', na_values=['', ' '], keep_default_na=True, skipinitialspace=True)
_pd_dtypes = {'Country': 'string', 'Number approved': 'Int64', 'Number declined': 'Int64', 'Total applications': 'Int64', 'Approval rate': 'Float64', 'Applications_log10': 'Float64'}
for _col, _dt in _pd_dtypes.items():
    if _col not in df.columns:
        continue
    try:
        if _dt in ('Int64', 'Float64'):
            df[_col] = pd.to_numeric(df[_col], errors='coerce').astype(_dt)
        else:
            df[_col] = df[_col].astype(_dt)
    except Exception:  # leave column as-is on failure
        pass
context['1587:1'] = df

################################################################################################################################################################
## Joiner # `1547`
# Node state: `EXECUTED`
# Input: [Port 2] 1545:1 from CSV Reader #1545; [Port 1] 1587:1 from CSV Reader #1587
# Output: [Port 1] 1547:1 to 1556 Column Appender #1556
# https://hub.knime.com/knime/extensions/org.knime.features.base/latest/org.knime.base.node.preproc.joiner3.Joiner3NodeFactory
df_left = context['1587:1']
df_right = context['1545:1']
_join_how = 'inner'
_join_suffix = ' (Right)'
_left_selected = ['Country', 'Approval rate', 'Number_Log']
_left_deselected = ['Number approved', 'Number declined', 'Total applications']
_left_include_unknown = True
_right_selected = ['WHO_Region', 'WHO_Life_Expectancy_at_Birth_years', 'WHO_Under5_Mortality_per_1000_live_births', 'WHO_Maternal_Mortality_per_100000_live_births', 'WHO_Physician_Density_per_10000_population', 'WHO_DTP3_Immunization_Coverage_pct']
_right_deselected = ['Country', 'WHO_Official_Name', 'WHO_GEO_M49', 'WHO_Life_Expectancy_Year', 'WHO_Healthy_Life_Expectancy_at_Birth_years', 'WHO_Healthy_Life_Expectancy_Year', 'WHO_Under5_Mortality_Year', 'WHO_Maternal_Mortality_Year', 'WHO_DTP3_Year', 'WHO_Physician_Density_Year', 'WHO_Source_URLs']
_right_include_unknown = False
_left_keys = [{'column': 'Country', 'row_id': False}]
_right_keys = [{'column': 'Country', 'row_id': False}]

def _jn_select_columns(df, selected, deselected, include_unknown):
    existing = list(df.columns)
    if selected:
        cols = [c for c in selected if c in df.columns]
        if include_unknown:
            known = set(selected) | set(deselected)
            cols.extend([c for c in existing if c not in known and c not in cols])
    else:
        cols = existing
    if deselected:
        cols = [c for c in cols if c not in set(deselected)]
    return cols

left_cols = _jn_select_columns(df_left, _left_selected, _left_deselected, _left_include_unknown)
right_cols = _jn_select_columns(df_right, _right_selected, _right_deselected, _right_include_unknown)
left_df = df_left[left_cols].copy()
right_df = df_right[right_cols].copy()

if not _left_keys or not _right_keys or len(_left_keys) != len(_right_keys):
    out_df = left_df.copy()
else:
    _left_on = []
    _right_on = []
    for _i, (_lk, _rk) in enumerate(zip(_left_keys, _right_keys)):
        _l_tmp = f'__k2p_join_left_{_i}__'
        _r_tmp = f'__k2p_join_right_{_i}__'
        left_df[_l_tmp] = df_left.index.astype('string') if _lk.get('row_id') else df_left[_lk['column']].astype('string')
        right_df[_r_tmp] = df_right.index.astype('string') if _rk.get('row_id') else df_right[_rk['column']].astype('string')
        _left_on.append(_l_tmp)
        _right_on.append(_r_tmp)
    _right_rename = {}
    _left_visible = set(left_cols)
    for _col in right_cols:
        if _col in _left_visible:
            _right_rename[_col] = f'{_col}{_join_suffix}'
    if _right_rename:
        right_df = right_df.rename(columns=_right_rename)
    out_df = pd.merge(left_df, right_df, how=_join_how, left_on=_left_on, right_on=_right_on, sort=False)
    out_df = out_df.drop(columns=_left_on + _right_on, errors='ignore')
context['1547:1'] = out_df

################################################################################################################################################################
## Joiner # `1551`
# Node state: `EXECUTED`
# Input: [Port 2] 1546:1 from CSV Reader #1546; [Port 1] 1587:1 from CSV Reader #1587
# Output: [Port 1] 1551:1 to 1556 Column Appender #1556
# https://hub.knime.com/knime/extensions/org.knime.features.base/latest/org.knime.base.node.preproc.joiner3.Joiner3NodeFactory
df_left = context['1587:1']
df_right = context['1546:1']
_join_how = 'inner'
_join_suffix = ' (Right)'
_left_selected = ['Approval rate']
_left_deselected = ['Country', 'Number approved', 'Number declined', 'Total applications', 'Applications_log10']
_left_include_unknown = True
_right_selected = ['Region', 'UN M49', 'World Bank', 'WB_FY2026_Region', 'WB_FY2026_Income_Group', 'WB_FY2026_Lending_Category', 'GDP_per_capita_current_USD', 'Life_expectancy_at_birth_years', 'Internet_users_pct_population', 'Urban_population_pct', 'GNI_per_capita_Atlas_current_USD']
_right_deselected = ['Country', 'WB_Code', 'WB_Official_Name', 'Population_Total', 'Population_Total_Year', 'GDP_per_capita_current_USD_Year', 'GNI_per_capita_Atlas_current_USD_Year', 'Life_expectancy_at_birth_years_Year', 'Internet_users_pct_population_Year', 'Urban_population_pct_Year', 'Reference']
_right_include_unknown = True
_left_keys = [{'column': 'Country', 'row_id': False}]
_right_keys = [{'column': 'Country', 'row_id': False}]

def _jn_select_columns(df, selected, deselected, include_unknown):
    existing = list(df.columns)
    if selected:
        cols = [c for c in selected if c in df.columns]
        if include_unknown:
            known = set(selected) | set(deselected)
            cols.extend([c for c in existing if c not in known and c not in cols])
    else:
        cols = existing
    if deselected:
        cols = [c for c in cols if c not in set(deselected)]
    return cols

left_cols = _jn_select_columns(df_left, _left_selected, _left_deselected, _left_include_unknown)
right_cols = _jn_select_columns(df_right, _right_selected, _right_deselected, _right_include_unknown)
left_df = df_left[left_cols].copy()
right_df = df_right[right_cols].copy()

if not _left_keys or not _right_keys or len(_left_keys) != len(_right_keys):
    out_df = left_df.copy()
else:
    _left_on = []
    _right_on = []
    for _i, (_lk, _rk) in enumerate(zip(_left_keys, _right_keys)):
        _l_tmp = f'__k2p_join_left_{_i}__'
        _r_tmp = f'__k2p_join_right_{_i}__'
        left_df[_l_tmp] = df_left.index.astype('string') if _lk.get('row_id') else df_left[_lk['column']].astype('string')
        right_df[_r_tmp] = df_right.index.astype('string') if _rk.get('row_id') else df_right[_rk['column']].astype('string')
        _left_on.append(_l_tmp)
        _right_on.append(_r_tmp)
    _right_rename = {}
    _left_visible = set(left_cols)
    for _col in right_cols:
        if _col in _left_visible:
            _right_rename[_col] = f'{_col}{_join_suffix}'
    if _right_rename:
        right_df = right_df.rename(columns=_right_rename)
    out_df = pd.merge(left_df, right_df, how=_join_how, left_on=_left_on, right_on=_right_on, sort=False)
    out_df = out_df.drop(columns=_left_on + _right_on, errors='ignore')
context['1551:1'] = out_df

################################################################################################################################################################
## Scatter Plot # `1572`
# Node state: `EXECUTED`
# Input: [Port 1] 1587:1 from CSV Reader #1587
# https://hub.knime.com/knime/extensions/org.knime.features.base/latest/org.knime.base.views.node.scatterplot.ScatterPlotNodeFactory
df = context['1587:1']  # input table
_x_col = 'Applications_log10'
_y_col = 'Approval rate'
_color_col = None
_title = 'Scatter Plot'
_x_label = 'Applications_log10'
_y_label = 'Approval rate'
_width_in = 800 / 100.0
_height_in = 600 / 100.0
_img_fmt = 'SVG'
_max_rows = int(2500)
_point_size = int(15)
_show_legend = True
_axis_extent_method = 'AUTO'
_manual_xlim = (0.0, 100.0)
_manual_ylim = (0.0, 100.0)

if _x_col is None or _x_col not in df.columns:
    raise KeyError(f'Scatter Plot: x-axis column not found: {_x_col!r}')
if _y_col is None or _y_col not in df.columns:
    raise KeyError(f'Scatter Plot: y-axis column not found: {_y_col!r}')
plot_df = df.head(_max_rows).copy() if _max_rows > 0 else df.copy()
x = pd.to_numeric(plot_df[_x_col], errors='coerce')
y = pd.to_numeric(plot_df[_y_col], errors='coerce')
valid = x.notna() & y.notna()
plot_df = plot_df.loc[valid].copy()
x = x.loc[valid]
y = y.loc[valid]

_green_blue = LinearSegmentedColormap.from_list('knime2py_green_blue', ['#2ca25f', '#2b8cbe'])
color_values = None
if _color_col and _color_col in plot_df.columns:
    c_num = pd.to_numeric(plot_df[_color_col], errors='coerce')
    if c_num.notna().any():
        color_values = c_num
    else:
        color_values = pd.Series(pd.factorize(plot_df[_color_col].astype('string'))[0], index=plot_df.index)

fig, ax = plt.subplots(figsize=(_width_in, _height_in), dpi=100)
if color_values is not None:
    sc = ax.scatter(x, y, c=color_values, cmap=_green_blue, s=_point_size, alpha=0.85, edgecolors='none')
    if _show_legend:
        cbar = fig.colorbar(sc, ax=ax)
        cbar.set_label(_color_col)
else:
    ax.scatter(x, y, color='#2b8cbe', s=_point_size, alpha=0.85, edgecolors='none')
ax.set_title(_title)
ax.set_xlabel(_x_label)
ax.set_ylabel(_y_label)
if _axis_extent_method == 'MANUAL':
    ax.set_xlim(*_manual_xlim)
    ax.set_ylim(*_manual_ylim)
ax.grid(True, linewidth=0.5, alpha=0.35)
fig.tight_layout()

try:
    out_dir = Path.cwd()
    out_dir.mkdir(parents=True, exist_ok=True)
except Exception:
    out_dir = Path(tempfile.gettempdir()) / 'knime2py_scatter'
    out_dir.mkdir(parents=True, exist_ok=True)
ext = 'svg' if str(_img_fmt).upper() == 'SVG' else 'png'
img_path = out_dir / ('scatter_1572.' + ext)
fig.savefig(img_path, bbox_inches='tight')
plt.close(fig)
print(f'[Scatter Plot] Wrote image to: {img_path}')

################################################################################################################################################################
## CSV Reader # `1591`
# Node state: `EXECUTED`
# Output: [Port 1] 1591:1 to 1592 Joiner #1592
# comments: UN_M49.csv
# https://hub.knime.com/knime/extensions/org.knime.features.base/latest/org.knime.base.node.io.filehandling.csv.reader.CSVTableReaderNodeFactory
csv_path = Path(r"data/original/un_m49_regions.csv")
# Note: escapechar equals quotechar; omitting escapechar and relying on double-quoted escapes.
df = pd.read_csv(csv_path, sep=',', quotechar='"', header=0, encoding='UTF-8', na_values=['', ' '], keep_default_na=True, skipinitialspace=True)
_pd_dtypes = {'Country': 'string', 'UN M49': 'string'}
for _col, _dt in _pd_dtypes.items():
    if _col not in df.columns:
        continue
    try:
        if _dt in ('Int64', 'Float64'):
            df[_col] = pd.to_numeric(df[_col], errors='coerce').astype(_dt)
        else:
            df[_col] = df[_col].astype(_dt)
    except Exception:  # leave column as-is on failure
        pass
context['1591:1'] = df

################################################################################################################################################################
## Joiner # `1592`
# Node state: `EXECUTED`
# Input: [Port 1] 1587:1 from CSV Reader #1587; [Port 2] 1591:1 from CSV Reader #1591
# Output: [Port 1] 1592:1 to 1556 Column Appender #1556
# https://hub.knime.com/knime/extensions/org.knime.features.base/latest/org.knime.base.node.preproc.joiner3.Joiner3NodeFactory
df_left = context['1587:1']
df_right = context['1591:1']
_join_how = 'inner'
_join_suffix = ' (Right)'
_left_selected = []
_left_deselected = ['Country', 'Number approved', 'Number declined', 'Total applications', 'Approval rate', 'Applications_log10']
_left_include_unknown = True
_right_selected = ['UN M49']
_right_deselected = ['Country']
_right_include_unknown = False
_left_keys = [{'column': 'Country', 'row_id': False}]
_right_keys = [{'column': 'Country', 'row_id': False}]

def _jn_select_columns(df, selected, deselected, include_unknown):
    existing = list(df.columns)
    if selected:
        cols = [c for c in selected if c in df.columns]
        if include_unknown:
            known = set(selected) | set(deselected)
            cols.extend([c for c in existing if c not in known and c not in cols])
    else:
        cols = existing
    if deselected:
        cols = [c for c in cols if c not in set(deselected)]
    return cols

left_cols = _jn_select_columns(df_left, _left_selected, _left_deselected, _left_include_unknown)
right_cols = _jn_select_columns(df_right, _right_selected, _right_deselected, _right_include_unknown)
left_df = df_left[left_cols].copy()
right_df = df_right[right_cols].copy()

if not _left_keys or not _right_keys or len(_left_keys) != len(_right_keys):
    out_df = left_df.copy()
else:
    _left_on = []
    _right_on = []
    for _i, (_lk, _rk) in enumerate(zip(_left_keys, _right_keys)):
        _l_tmp = f'__k2p_join_left_{_i}__'
        _r_tmp = f'__k2p_join_right_{_i}__'
        left_df[_l_tmp] = df_left.index.astype('string') if _lk.get('row_id') else df_left[_lk['column']].astype('string')
        right_df[_r_tmp] = df_right.index.astype('string') if _rk.get('row_id') else df_right[_rk['column']].astype('string')
        _left_on.append(_l_tmp)
        _right_on.append(_r_tmp)
    _right_rename = {}
    _left_visible = set(left_cols)
    for _col in right_cols:
        if _col in _left_visible:
            _right_rename[_col] = f'{_col}{_join_suffix}'
    if _right_rename:
        right_df = right_df.rename(columns=_right_rename)
    out_df = pd.merge(left_df, right_df, how=_join_how, left_on=_left_on, right_on=_right_on, sort=False)
    out_df = out_df.drop(columns=_left_on + _right_on, errors='ignore')
context['1592:1'] = out_df

################################################################################################################################################################
## Column Appender # `1556`
# Node state: `EXECUTED`
# Input: [Port 1] 1547:1 from Joiner #1547; [Port 2] 1551:1 from Joiner #1551; [Port 3] 1592:1 from Joiner #1592
# Output: [Port 1] 1556:1 to 1561 Missing Value #1561
# https://hub.knime.com/knime/extensions/org.knime.features.base/latest/org.knime.base.node.preproc.columnappend2.ColumnAppender2NodeFactory
left_df = context['1547:1']  # left table
right_dfs = []
right_dfs.append(context['1551:1'])
right_dfs.append(context['1592:1'])
out_df = left_df.copy()
_mode = 'IDENTICAL'

def _unique_with_suffix(base: str, existing: set, suffix: str) -> str:
    if base not in existing:
        return base
    new = f"{base}{suffix}"
    # If even the suffixed name exists, keep appending the same suffix
    while new in existing:
        new = f"{new}{suffix}"
    return new

# Append each right table in order (1-based index for suffix)
for k, rdf in enumerate(right_dfs, start=1):
    suffix = f" (#{k})"
    # Build a collision-aware rename map guaranteeing uniqueness
    existing = set(out_df.columns)
    rename_map = {}
    for c in rdf.columns:
        if c in existing or c in rename_map.values():
            newc = _unique_with_suffix(c, existing | set(rename_map.values()), suffix)
            rename_map[c] = newc
        else:
            # no collision; keep original
            rename_map[c] = c
    right_safe = rdf.rename(columns=rename_map) if rename_map else rdf

    if _mode == 'IDENTICAL':
        # Align by index; if different, left-align by reindexing right to out_df.index
        if out_df.index.equals(right_safe.index):
            out_df = out_df.join(right_safe, how='left')
        else:
            out_df = out_df.join(right_safe.reindex(out_df.index), how='left')
    else:
        # Positional fallback for unknown modes
        out_df = pd.concat([out_df.reset_index(drop=True),
                           right_safe.reset_index(drop=True)], axis=1)
context['1556:1'] = out_df

################################################################################################################################################################
## Missing Value # `1561`
# Node state: `EXECUTED`
# Input: [Port 1] 1556:1 from Column Appender #1556
# Output: [Port 1] 1561:1 to 1557 Column Filter #1557
# https://hub.knime.com/knime/extensions/org.knime.features.base/latest/org.knime.base.node.preproc.pmml.missingval.compute.MissingValueHandlerNodeFactory
df = context['1556:1']  # input table
def _mv_dtype_key(series):
    if pd.api.types.is_integer_dtype(series):
        return 'int'
    if pd.api.types.is_float_dtype(series):
        return 'float'
    if pd.api.types.is_bool_dtype(series):
        return 'boolean'
    return 'string'

def _mv_policy_for(col_name, dtype_key, column_policies, dtype_policies):
    for pol in column_policies:
        if pol.get('column') == col_name:
            return pol
    for pol in dtype_policies:
        if pol.get('dtype') == dtype_key:
            return pol
    return None

def _mv_resolve_value(series, policy, dtype_key):
    if policy is None:
        return None
    strat = (policy.get('strategy') or '').lower()
    if strat == 'fixed':
        val = policy.get('value')
    elif strat == 'mean':
        val = series.mean(skipna=True)
    elif strat == 'median':
        val = series.median(skipna=True)
    elif strat == 'mode':
        mode = series.mode(dropna=True)
        val = mode.iloc[0] if not mode.empty else None
    else:
        val = policy.get('value')
    if val is None or (isinstance(val, float) and pd.isna(val)):
        return None
    if dtype_key == 'int':
        try:
            val = int(round(float(val)))
        except Exception:
            return None
        return str(val), 'integer'
    if dtype_key == 'float':
        try:
            val = float(val)
        except Exception:
            return None
        return str(val), 'double'
    if dtype_key == 'boolean':
        text = str(val).strip().lower()
        val_int = '1' if text in {'true','1','t','y','yes'} else '0'
        return val_int, 'integer'
    return str(val), 'string'

def _mv_collect_bundle(source_df, column_policies, dtype_policies):
    df = source_df
    data_entries = []
    transforms = []
    for col in df.columns:
        series = df[col]
        dtype_key = _mv_dtype_key(series)
        entry = {'name': str(col), 'dtype_key': dtype_key}
        if dtype_key == 'string':
            entry['optype'] = 'categorical'
            entry['dataType'] = 'string'
            values = series.dropna().astype(str).unique().tolist()
            if values:
                entry['values'] = [str(v) for v in values[:128]]
        else:
            entry['optype'] = 'continuous'
            entry['dataType'] = 'integer' if dtype_key in {'int','boolean'} else 'double'
            non_missing = series.dropna()
            if not non_missing.empty:
                try:
                    entry['interval'] = [float(non_missing.min()), float(non_missing.max())]
                except Exception:
                    pass
        data_entries.append(entry)
        policy = _mv_policy_for(col, dtype_key, column_policies, dtype_policies)
        resolved = _mv_resolve_value(series, policy, dtype_key)
        if resolved is None:
            continue
        const_text, const_dtype = resolved
        transforms.append({
            'column': str(col),
            'derived_name': f"{col}*",
            'const': const_text,
            'const_dtype': const_dtype,
            'optype': entry.get('optype', 'continuous'),
        })
    return {
        'model_type': 'missing_value',
        'version': '4.2',
        'application': {'name': 'knime2py', 'version': '1.0'},
        'data_dictionary': data_entries,
        'transformations': transforms,
    }
out_df = df.copy()
override_cols = {'GDP_per_capita_current_USD', 'WB_FY2026_Income_Group', 'WB_FY2026_Lending_Category', 'WHO_DTP3_Immunization_Coverage_pct', 'WHO_Life_Expectancy_at_Birth_years', 'WHO_Physician_Density_per_10000_population'}
if 'WHO_Life_Expectancy_at_Birth_years' in out_df.columns:
    out_df = out_df.dropna(subset=['WHO_Life_Expectancy_at_Birth_years'])
if 'WHO_DTP3_Immunization_Coverage_pct' in out_df.columns:
    out_df = out_df.dropna(subset=['WHO_DTP3_Immunization_Coverage_pct'])
if 'GDP_per_capita_current_USD' in out_df.columns:
    out_df = out_df.dropna(subset=['GDP_per_capita_current_USD'])
if 'WB_FY2026_Income_Group' in out_df.columns:
    out_df['WB_FY2026_Income_Group'] = out_df['WB_FY2026_Income_Group'].fillna('Missing')
if 'WB_FY2026_Lending_Category' in out_df.columns:
    out_df['WB_FY2026_Lending_Category'] = out_df['WB_FY2026_Lending_Category'].fillna('Missing')
if 'WHO_Physician_Density_per_10000_population' in out_df.columns:
    out_df = out_df.dropna(subset=['WHO_Physician_Density_per_10000_population'])
int_cols = [c for c in out_df.select_dtypes(include=['Int64','Int32','Int16','int64','int32','int16']).columns if c not in override_cols]
if len(int_cols) > 0:
    pass  # No fixed value configured for ints; skipping
float_cols = [c for c in out_df.select_dtypes(include=['float64','float32']).columns if c not in override_cols]
if len(float_cols) > 0:
    pass  # No fixed value configured for floats; skipping
str_cols = [c for c in out_df.select_dtypes(include=['string','object']).columns if c not in override_cols]
if len(str_cols) > 0:
    pass  # No fixed value configured for strings; skipping
dtype_policies = [{'dtype': 'int', 'strategy': 'fixed', 'value': None}, {'dtype': 'string', 'strategy': 'fixed', 'value': None}, {'dtype': 'float', 'strategy': 'fixed', 'value': None}]
column_policies = [{'column': 'WHO_Life_Expectancy_at_Birth_years', 'dtype': None, 'strategy': 'drop', 'value': None}, {'column': 'WHO_DTP3_Immunization_Coverage_pct', 'dtype': None, 'strategy': 'drop', 'value': None}, {'column': 'GDP_per_capita_current_USD', 'dtype': None, 'strategy': 'drop', 'value': None}, {'column': 'WB_FY2026_Income_Group', 'dtype': 'string', 'strategy': 'fixed', 'value': 'Missing'}, {'column': 'WB_FY2026_Lending_Category', 'dtype': 'string', 'strategy': 'fixed', 'value': 'Missing'}, {'column': 'WHO_Physician_Density_per_10000_population', 'dtype': None, 'strategy': 'drop', 'value': None}]
model_bundle = _mv_collect_bundle(df, column_policies, dtype_policies)
model_bundle['strategies'] = dtype_policies
model_bundle['column_strategies'] = column_policies
context['1561:1'] = out_df

################################################################################################################################################################
## Column Filter # `1557`
# Node state: `EXECUTED`
# Input: [Port 1] 1561:1 from Missing Value #1561
# Output: [Port 1] 1557:1 to 1552 Linear Correlation #1552; [Port 1] 1557:1 to 1575 Row Filter #1575
# https://hub.knime.com/knime/extensions/org.knime.features.base/latest/org.knime.base.node.preproc.filter.column2.ColumnFilter2NodeFactory
df = context['1561:1']  # input table
out_df = df
exclude_cols = ['WHO_Life_Expectancy_at_Birth_years', 'Approval rate (#1)']
out_df = out_df.drop(columns=[c for c in exclude_cols if c in out_df.columns], errors='ignore')
context['1557:1'] = out_df

################################################################################################################################################################
## Linear Correlation # `1552`
# Node state: `EXECUTED`
# Input: [Port 1] 1557:1 from Column Filter #1557
# Output: [Port 1] 1552:1 to 1593 CSV Writer #1593
# https://hub.knime.com/knime/extensions/org.knime.features.base/latest/org.knime.base.node.preproc.correlation.compute2.CorrelationCompute2NodeFactory
df = context['1557:1']  # input table
out_df = df.copy()  # passthrough copy

# 1) Type buckets and eligible nominal limit
_pvc = int(50)
_num_like_all = df.select_dtypes(include=['number','Int64','Float64','bool','boolean']).columns.tolist()
_nom_cand_all = df.select_dtypes(include=['object','string','category']).columns.tolist()
_nom_eligible_all = []
for _c in _nom_cand_all:
    _k = int(df[_c].astype('string').nunique(dropna=True))
    if _k <= _pvc:
        _nom_eligible_all.append(_c)

# 2) Establish the SOURCE ORDER
_included_cfg = ['Approval rate', 'WHO_Under5_Mortality_per_1000_live_births', 'WHO_Maternal_Mortality_per_100000_live_births', 'WHO_Physician_Density_per_10000_population', 'WHO_DTP3_Immunization_Coverage_pct', 'GDP_per_capita_current_USD', 'Life_expectancy_at_birth_years', 'Internet_users_pct_population', 'Urban_population_pct', 'GNI_per_capita_Atlas_current_USD']
_excluded_cfg = ['Country', 'Applications_log10', 'WHO_Region', 'WB_FY2026_Region', 'WB_FY2026_Income_Group', 'WB_FY2026_Lending_Category', 'UN M49']
_enforce = 'EnforceExclusion'
if _enforce == 'EnforceInclusion' and len(_included_cfg) > 0:
    # Exact order from settings.xml (filtered to existing columns)
    _order_source = [c for c in _included_cfg if c in out_df.columns]
else:
    # Input table order
    _order_source = list(df.columns)

# 3) Apply include/exclude and compatibility (no reordering)
if _enforce == 'EnforceInclusion' and len(_included_cfg) > 0:
    _union = [c for c in _order_source if c in _included_cfg]
else:  # EnforceExclusion
    _union = [c for c in _order_source if c not in set(_excluded_cfg)]

# Buckets in SOURCE order
_num_like = [c for c in _union if c in _num_like_all]
_nom_eligible = [c for c in _union if c in _nom_eligible_all]

# 4) Build Port-1 measure rows in SOURCE order
_pairs_mode = 'COMPATIBLE_PAIRS'  # 'COMPATIBLE_PAIRS' | 'ALL_PAIRS'
pairs = []
for i in range(len(_union)):
    for j in range(i+1, len(_union)):
        a, b = _union[i], _union[j]
        if _pairs_mode == 'COMPATIBLE_PAIRS':
            # Keep order; only add if both numeric or both eligible nominal
            if (a in _num_like and b in _num_like) or (a in _nom_eligible and b in _nom_eligible):
                pairs.append((a, b))
        else:  # ALL_PAIRS
            pairs.append((a, b))

# Early-empty check
if len(pairs) == 0:
    measure_out = pd.DataFrame(columns=[
        'First column name', 'Second column name', 'Correlation value', 'p value', 'Degrees of freedom'
    ])
else:
    try:
        _have_scipy = True
    except Exception:
        _have_scipy = False
    _alt = 'TWO_SIDED'

    def _encode_series(s):
        # Nominal → ordered integers with NaN preserved; numeric/bool → float64
        if s.dtype.name in ('object','string') or str(s.dtype).startswith('category'):
            _u = pd.Series(sorted(s.dropna().astype('string').unique()), dtype='string')
            _map = {v:i for i,v in enumerate(_u.tolist())}
            _enc = s.astype('string').map(_map)
            return _enc.astype('float64')
        return pd.to_numeric(s, errors='coerce').astype('float64')

    rows = []
    for a, b in pairs:
        _sa_raw = df[a]
        _sb_raw = df[b]
        a_is_num = (a in _num_like)
        b_is_num = (b in _num_like)
        a_is_nom = (a in _nom_eligible)
        b_is_nom = (b in _nom_eligible)
        _sa = _encode_series(_sa_raw)
        _sb = _encode_series(_sb_raw)
        pair_df = pd.concat([_sa, _sb], axis=1).dropna()
        n = int(len(pair_df))
        if n < 2:
            r_val = np.nan; p_val = np.nan; dof = np.nan
        else:
            dof = n - 2
            # Correlation value (always Pearson on encoded data)
            if _have_scipy and a_is_num and b_is_num:
                try:
                    r_val, p_two = _sstats.pearsonr(pair_df.iloc[:,0].to_numpy(), pair_df.iloc[:,1].to_numpy())
                except Exception:
                    r_val = pair_df.iloc[:,0].corr(pair_df.iloc[:,1])
                    p_two = np.nan
            else:
                r_val = pair_df.iloc[:,0].corr(pair_df.iloc[:,1])
                p_two = np.nan

            # p-value policy:
            # - numeric↔numeric: use SciPy p (with alternative remap) when available, else NaN
            # - nominal↔nominal: KNIME shows p=0 → force 0.0
            if a_is_nom and b_is_nom:
                p_val = 0.0
            elif np.isnan(p_two):
                p_val = np.nan
            else:
                if _alt == 'TWO_SIDED':
                    p_val = float(p_two)
                elif _alt == 'GREATER':
                    p_val = float(p_two/2.0) if r_val >= 0 else float(1.0 - p_two/2.0)
                elif _alt == 'LESS':
                    p_val = float(p_two/2.0) if r_val <= 0 else float(1.0 - p_two/2.0)
                else:
                    p_val = float(p_two)

        rows.append({
            'First column name': a,
            'Second column name': b,
            'Correlation value': r_val,
            'p value': p_val,
            'Degrees of freedom': dof,
        })
    measure_out = pd.DataFrame(rows)
    # Do NOT sort — retain insertion order (matches KNIME)

# 5) Port 2 — numeric Pearson matrix in SOURCE order
_num_cols_ordered = [c for c in _union if c in _num_like]
if len(_num_cols_ordered) >= 1:
    _Xnum = df[_num_cols_ordered].apply(pd.to_numeric, errors='coerce').astype('float64')
    matrix_out = _Xnum.corr(method='pearson')
else:
    matrix_out = pd.DataFrame(index=pd.Index(_num_cols_ordered, name=None), columns=_num_cols_ordered, dtype='float64')

# 6) Port 3 — model
model_out = {
    'type': 'CorrelationModel',
    'method': 'pearson',
    'alternative': _alt if len(pairs) else 'TWO_SIDED',
    'columns': _union,
    'matrix': matrix_out.copy(),
}

port1 = measure_out
port2 = matrix_out
port3 = model_out
context['1552:1'] = port1
context['1552:2'] = port2
context['1552:3'] = port3

################################################################################################################################################################
## Row Filter # `1575`
# Node state: `CONFIGURED`
# Input: [Port 1] 1557:1 from Column Filter #1557
# Output: [Port 1] 1575:1 to 1586 CSV Writer #1586
# https://hub.knime.com/knime/extensions/org.knime.features.base/latest/org.knime.base.node.preproc.filter.row3.RowFilterNodeFactory
df = context['1557:1']  # input table
def _rf_norm_name(s):
    return _re.sub(r'[^a-z0-9]+', '', str(s).lower())
_RF_LCMAP = {c.lower(): c for c in df.columns}
_RF_NORMMAP = {_rf_norm_name(c): c for c in df.columns}

def _rf_resolve(name):
    if name in df.columns:
        return name
    if name is None:
        return None
    c = _RF_LCMAP.get(str(name).lower())
    if c is not None:
        return c
    key = _rf_norm_name(name)
    c = _RF_NORMMAP.get(key)
    if c is not None:
        return c
    # Heuristic aliases for common aggregate column names
    if key in {'occurrencecount','count','rowcount'}:
        cand = [col for col in df.columns if 'count' in _rf_norm_name(col)]
        if len(cand) == 1:
            return cand[0]
    return None

def _rf_to_num(val):
    s = pd.Series([val])
    v = pd.to_numeric(s, errors='coerce').iloc[0]
    return v

mask = pd.Series(True, index=df.index)
_col0 = _rf_resolve('Applications_log10')
if _col0 is None:
    _c0 = pd.Series(True, index=df.index)  # missing column → neutral
else:
    _s0 = df[_col0]
    _c0 = pd.to_numeric(_s0, errors='coerce') > _rf_to_num('1.0')
mask = (mask & _c0)
_invert = False
final_mask = (~mask) if _invert else mask
out_df = df[final_mask].copy()
context['1575:1'] = out_df

################################################################################################################################################################
## CSV Writer # `1586`
# Node state: `CONFIGURED`
# Input: [Port 1] 1575:1 from Row Filter #1575
# comments: Combined.csv
# https://hub.knime.com/knime/extensions/org.knime.features.base/latest/org.knime.base.node.io.filehandling.csv.writer.CSVWriter2NodeFactory
df = context['1575:1']
out_path = Path(r"data/prepared/inz_2022-2025_wb_who_m49_combined.csv")
df = df.copy()
for _col in df.select_dtypes(include=['datetime', 'datetimetz']).columns:
    df[_col] = df[_col].dt.strftime('%Y-%m-%dT%H:%M')
def _k2p_format_timedelta(_value):
    if pd.isna(_value):
        return pd.NA
    _total_minutes = int(pd.Timedelta(_value).total_seconds() // 60)
    if _total_minutes == 0:
        return 'PT0S'
    _sign = -1 if _total_minutes < 0 else 1
    _hours, _minutes = divmod(abs(_total_minutes), 60)
    if _sign < 0:
        if _hours and _minutes:
            return f'PT-{_hours}H-{_minutes}M'
        if _hours:
            return f'PT-{_hours}H'
        return f'PT-{_minutes}M'
    if _hours and _minutes:
        return f'PT{_hours}H{_minutes}M'
    if _hours:
        return f'PT{_hours}H'
    return f'PT{_minutes}M'
for _col in df.select_dtypes(include=['timedelta']).columns:
    df[_col] = df[_col].map(_k2p_format_timedelta)
for _col in df.select_dtypes(include=['float']).columns:
    _series = df[_col].dropna()
    if not _series.empty and ((_series % 1) == 0).all():
        df[_col] = df[_col].astype('Int64')
_k2p_missing_sentinel = '__K2P_MISSING_FIELD_9b1f6f7c__'
df = df.astype('object').mask(df.isna(), _k2p_missing_sentinel)
df.to_csv(out_path, sep=',', quotechar='"', header=True, encoding='UTF-8', na_rep='', index=False, quoting=csv.QUOTE_NONNUMERIC)
_k2p_csv_text = out_path.read_text(encoding='UTF-8')
_k2p_csv_text = _k2p_csv_text.replace('"' + _k2p_missing_sentinel + '"', '')
out_path.write_text(_k2p_csv_text, encoding='UTF-8')

################################################################################################################################################################
## CSV Writer # `1593`
# Node state: `CONFIGURED`
# Input: [Port 1] 1552:1 from Linear Correlation #1552
# comments: Combined.csv
# https://hub.knime.com/knime/extensions/org.knime.features.base/latest/org.knime.base.node.io.filehandling.csv.writer.CSVWriter2NodeFactory
df = context['1552:1']
out_path = Path(r"data/results/Combined-correlation-output.csv")
df = df.copy()
for _col in df.select_dtypes(include=['datetime', 'datetimetz']).columns:
    df[_col] = df[_col].dt.strftime('%Y-%m-%dT%H:%M')
def _k2p_format_timedelta(_value):
    if pd.isna(_value):
        return pd.NA
    _total_minutes = int(pd.Timedelta(_value).total_seconds() // 60)
    if _total_minutes == 0:
        return 'PT0S'
    _sign = -1 if _total_minutes < 0 else 1
    _hours, _minutes = divmod(abs(_total_minutes), 60)
    if _sign < 0:
        if _hours and _minutes:
            return f'PT-{_hours}H-{_minutes}M'
        if _hours:
            return f'PT-{_hours}H'
        return f'PT-{_minutes}M'
    if _hours and _minutes:
        return f'PT{_hours}H{_minutes}M'
    if _hours:
        return f'PT{_hours}H'
    return f'PT{_minutes}M'
for _col in df.select_dtypes(include=['timedelta']).columns:
    df[_col] = df[_col].map(_k2p_format_timedelta)
for _col in df.select_dtypes(include=['float']).columns:
    _series = df[_col].dropna()
    if not _series.empty and ((_series % 1) == 0).all():
        df[_col] = df[_col].astype('Int64')
_k2p_missing_sentinel = '__K2P_MISSING_FIELD_9b1f6f7c__'
df = df.astype('object').mask(df.isna(), _k2p_missing_sentinel)
df.to_csv(out_path, sep=',', quotechar='"', header=True, encoding='UTF-8', na_rep='', index=False, quoting=csv.QUOTE_NONNUMERIC)
_k2p_csv_text = out_path.read_text(encoding='UTF-8')
_k2p_csv_text = _k2p_csv_text.replace('"' + _k2p_missing_sentinel + '"', '')
out_path.write_text(_k2p_csv_text, encoding='UTF-8')
