# ====================================================================================================
# knime2py — KNIME → Python workbook
# Workflow: INZ_visa_decisions_unification__g01
# Source:   /work/INZ_visa_decisions_unification/workflow.knime
#
# This file was generated by the open-source knime2py project (KNIME → Python codegen).
# GitHub: https://github.com/vitalii-kaplan/knime2py
#
# Notes:
# • The code below is a linear translation of KNIME nodes into Python sections.
# • A lightweight `context` dict is available for debugging/inspection of intermediate tables.
#
# Export coverage:
# • All nodes successfully exported.
# ====================================================================================================

from pathlib import Path
import csv
import numpy as np
import pandas as pd
import re as _re

# Simple shared context to pass tabular data between sections (for debugging)
context = {}  # e.g., {'<node_id>:<port>': df}

################################################################################################################################################################
## CSV Reader # `1510`
# Node state: `EXECUTED`
# Output: [Port 1] 1510:1 to 1514 Column Filter #1514
# comments: 2022
# https://hub.knime.com/knime/extensions/org.knime.features.base/latest/org.knime.base.node.io.filehandling.csv.reader.CSVTableReaderNodeFactory
csv_path = Path(r"data/original/inz_student_visa_decisions_2022.csv")
# Note: escapechar equals quotechar; omitting escapechar and relying on double-quoted escapes.
df = pd.read_csv(csv_path, sep=',', quotechar='"', header=0, encoding='UTF-8', na_values=['', ' '], keep_default_na=True, skipinitialspace=True)
_pd_dtypes = {'Applicant nationality': 'string', 'Number approved': 'string', 'Number declined': 'Int64', 'Decline rate': 'string'}
for _col, _dt in _pd_dtypes.items():
    if _col not in df.columns:
        continue
    try:
        if _dt in ('Int64', 'Float64'):
            df[_col] = pd.to_numeric(df[_col], errors='coerce').astype(_dt)
        else:
            df[_col] = df[_col].astype(_dt)
    except Exception:  # leave column as-is on failure
        pass
context['1510:1'] = df

################################################################################################################################################################
## CSV Reader # `1511`
# Node state: `EXECUTED`
# Output: [Port 1] 1511:1 to 1515 Column Filter #1515
# comments: 2023
# https://hub.knime.com/knime/extensions/org.knime.features.base/latest/org.knime.base.node.io.filehandling.csv.reader.CSVTableReaderNodeFactory
csv_path = Path(r"data/original/inz_student_visa_decisions_2023.csv")
# Note: escapechar equals quotechar; omitting escapechar and relying on double-quoted escapes.
df = pd.read_csv(csv_path, sep=',', quotechar='"', header=0, encoding='UTF-8', na_values=['', ' '], keep_default_na=True, skipinitialspace=True)
_pd_dtypes = {'Country': 'string', 'Volume of visa applications': 'Int64', 'Number approved': 'Int64', 'Approval rate': 'string', 'Number declined': 'Int64', 'Decline rate': 'string'}
for _col, _dt in _pd_dtypes.items():
    if _col not in df.columns:
        continue
    try:
        if _dt in ('Int64', 'Float64'):
            df[_col] = pd.to_numeric(df[_col], errors='coerce').astype(_dt)
        else:
            df[_col] = df[_col].astype(_dt)
    except Exception:  # leave column as-is on failure
        pass
context['1511:1'] = df

################################################################################################################################################################
## CSV Reader # `1512`
# Node state: `EXECUTED`
# Output: [Port 1] 1512:1 to 1516 Column Filter #1516
# comments: 2024
# https://hub.knime.com/knime/extensions/org.knime.features.base/latest/org.knime.base.node.io.filehandling.csv.reader.CSVTableReaderNodeFactory
csv_path = Path(r"data/original/inz_student_visa_decisions_2024.csv")
# Note: escapechar equals quotechar; omitting escapechar and relying on double-quoted escapes.
df = pd.read_csv(csv_path, sep=',', quotechar='"', header=0, encoding='UTF-8', na_values=['', ' '], keep_default_na=True, skipinitialspace=True)
_pd_dtypes = {'Country': 'string', 'Volume of visa applications': 'Int64', 'Number approved': 'Int64', 'Approval rate': 'string', 'Number declined': 'Int64', 'Decline rate': 'string'}
for _col, _dt in _pd_dtypes.items():
    if _col not in df.columns:
        continue
    try:
        if _dt in ('Int64', 'Float64'):
            df[_col] = pd.to_numeric(df[_col], errors='coerce').astype(_dt)
        else:
            df[_col] = df[_col].astype(_dt)
    except Exception:  # leave column as-is on failure
        pass
context['1512:1'] = df

################################################################################################################################################################
## CSV Reader # `1513`
# Node state: `EXECUTED`
# Output: [Port 1] 1513:1 to 1517 Column Filter #1517
# comments: 2025
# https://hub.knime.com/knime/extensions/org.knime.features.base/latest/org.knime.base.node.io.filehandling.csv.reader.CSVTableReaderNodeFactory
csv_path = Path(r"data/original/inz_student_visa_decisions_2025.csv")
# Note: escapechar equals quotechar; omitting escapechar and relying on double-quoted escapes.
df = pd.read_csv(csv_path, sep=',', quotechar='"', header=0, encoding='UTF-8', na_values=['', ' '], keep_default_na=True, skipinitialspace=True)
_pd_dtypes = {'Country name': 'string', 'Volume of visa applications': 'Int64', 'Number approved': 'Int64', 'Approval rate': 'string', 'Number declined': 'Int64', 'Decline rate': 'string'}
for _col, _dt in _pd_dtypes.items():
    if _col not in df.columns:
        continue
    try:
        if _dt in ('Int64', 'Float64'):
            df[_col] = pd.to_numeric(df[_col], errors='coerce').astype(_dt)
        else:
            df[_col] = df[_col].astype(_dt)
    except Exception:  # leave column as-is on failure
        pass
context['1513:1'] = df

################################################################################################################################################################
## Column Filter # `1514`
# Node state: `EXECUTED`
# Input: [Port 1] 1510:1 from CSV Reader #1510
# Output: [Port 1] 1514:1 to 1518 Column Renamer #1518
# https://hub.knime.com/knime/extensions/org.knime.features.base/latest/org.knime.base.node.preproc.filter.column2.ColumnFilter2NodeFactory
df = context['1510:1']  # input table
out_df = df
exclude_cols = ['Decline rate']
out_df = out_df.drop(columns=[c for c in exclude_cols if c in out_df.columns], errors='ignore')
context['1514:1'] = out_df

################################################################################################################################################################
## Column Filter # `1515`
# Node state: `EXECUTED`
# Input: [Port 1] 1511:1 from CSV Reader #1511
# Output: [Port 1] 1515:1 to 1520 Column Resorter #1520
# https://hub.knime.com/knime/extensions/org.knime.features.base/latest/org.knime.base.node.preproc.filter.column2.ColumnFilter2NodeFactory
df = context['1511:1']  # input table
out_df = df
exclude_cols = ['Decline rate', 'Volume of visa applications', 'Approval rate']
out_df = out_df.drop(columns=[c for c in exclude_cols if c in out_df.columns], errors='ignore')
context['1515:1'] = out_df

################################################################################################################################################################
## Column Filter # `1516`
# Node state: `EXECUTED`
# Input: [Port 1] 1512:1 from CSV Reader #1512
# Output: [Port 1] 1516:1 to 1521 Column Resorter #1521
# https://hub.knime.com/knime/extensions/org.knime.features.base/latest/org.knime.base.node.preproc.filter.column2.ColumnFilter2NodeFactory
df = context['1512:1']  # input table
out_df = df
exclude_cols = ['Decline rate', 'Volume of visa applications', 'Approval rate']
out_df = out_df.drop(columns=[c for c in exclude_cols if c in out_df.columns], errors='ignore')
context['1516:1'] = out_df

################################################################################################################################################################
## Column Filter # `1517`
# Node state: `EXECUTED`
# Input: [Port 1] 1513:1 from CSV Reader #1513
# Output: [Port 1] 1517:1 to 1519 Column Renamer #1519
# https://hub.knime.com/knime/extensions/org.knime.features.base/latest/org.knime.base.node.preproc.filter.column2.ColumnFilter2NodeFactory
df = context['1513:1']  # input table
out_df = df
exclude_cols = ['Decline rate', 'Volume of visa applications', 'Approval rate']
out_df = out_df.drop(columns=[c for c in exclude_cols if c in out_df.columns], errors='ignore')
context['1517:1'] = out_df

################################################################################################################################################################
## Column Renamer # `1518`
# Node state: `EXECUTED`
# Input: [Port 1] 1514:1 from Column Filter #1514
# Output: [Port 1] 1518:1 to 1525 String to Number #1525
# https://hub.knime.com/knime/extensions/org.knime.features.base/latest/org.knime.base.node.preproc.column.renamer.ColumnRenamerNodeFactory
df = context['1514:1']  # input table
_pairs = [('Applicant nationality', 'Country')]
out_df = df.copy()
# Filter to pairs where the source column exists
present = [(o, n) for (o, n) in _pairs if o in out_df.columns]
if not present:
    final_map = {}
else:
    # Build a collision-safe mapping
    existing = set(out_df.columns)
    final_map = {}
    for old, new in present:
        # If renaming to the same name, keep it (no-op)
        tgt = new
        if tgt != old:
            if tgt in existing and tgt != old:
                base = tgt
                k = 1
                while f"{base}_{k}" in existing:
                    k += 1
                tgt = f"{base}_{k}"
            # update sets for subsequent checks
            existing.discard(old)
            existing.add(tgt)
        final_map[old] = tgt

# Apply rename if any
if final_map:
    out_df = out_df.rename(columns=final_map)
context['1518:1'] = out_df

################################################################################################################################################################
## Column Renamer # `1519`
# Node state: `EXECUTED`
# Input: [Port 1] 1517:1 from Column Filter #1517
# Output: [Port 1] 1519:1 to 1522 Column Resorter #1522
# https://hub.knime.com/knime/extensions/org.knime.features.base/latest/org.knime.base.node.preproc.column.renamer.ColumnRenamerNodeFactory
df = context['1517:1']  # input table
_pairs = [('Country name', 'Country')]
out_df = df.copy()
# Filter to pairs where the source column exists
present = [(o, n) for (o, n) in _pairs if o in out_df.columns]
if not present:
    final_map = {}
else:
    # Build a collision-safe mapping
    existing = set(out_df.columns)
    final_map = {}
    for old, new in present:
        # If renaming to the same name, keep it (no-op)
        tgt = new
        if tgt != old:
            if tgt in existing and tgt != old:
                base = tgt
                k = 1
                while f"{base}_{k}" in existing:
                    k += 1
                tgt = f"{base}_{k}"
            # update sets for subsequent checks
            existing.discard(old)
            existing.add(tgt)
        final_map[old] = tgt

# Apply rename if any
if final_map:
    out_df = out_df.rename(columns=final_map)
context['1519:1'] = out_df

################################################################################################################################################################
## Column Resorter # `1520`
# Node state: `EXECUTED`
# Input: [Port 1] 1515:1 from Column Filter #1515
# Output: [Port 1] 1520:1 to 1523 Concatenate #1523
# https://hub.knime.com/knime/extensions/org.knime.features.base/latest/org.knime.base.node.preproc.columnresorter.ColumnResorterNodeFactory
df = context['1515:1']  # input table
_column_order = ['Country', 'Number approved', 'Number declined', '<any unknown new column>']
_unknown_placeholder = '<any unknown new column>'
_seen = set()
_explicit = []
for _col in _column_order:
    if _col == _unknown_placeholder:
        continue
    if _col in df.columns and _col not in _seen:
        _explicit.append(_col)
        _seen.add(_col)
_remaining = [col for col in df.columns if col not in _seen]
if _unknown_placeholder in _column_order:
    _out_columns = []
    _remaining_inserted = False
    for _col in _column_order:
        if _col == _unknown_placeholder:
            if not _remaining_inserted:
                _out_columns.extend(_remaining)
                _remaining_inserted = True
        elif _col in df.columns and _col not in _out_columns:
            _out_columns.append(_col)
    if not _remaining_inserted:
        _out_columns.extend(_remaining)
else:
    _out_columns = _explicit + _remaining
out_df = df.loc[:, _out_columns].copy()
context['1520:1'] = out_df

################################################################################################################################################################
## Column Resorter # `1521`
# Node state: `EXECUTED`
# Input: [Port 1] 1516:1 from Column Filter #1516
# Output: [Port 1] 1521:1 to 1523 Concatenate #1523
# https://hub.knime.com/knime/extensions/org.knime.features.base/latest/org.knime.base.node.preproc.columnresorter.ColumnResorterNodeFactory
df = context['1516:1']  # input table
_column_order = ['Country', 'Number approved', 'Number declined', '<any unknown new column>']
_unknown_placeholder = '<any unknown new column>'
_seen = set()
_explicit = []
for _col in _column_order:
    if _col == _unknown_placeholder:
        continue
    if _col in df.columns and _col not in _seen:
        _explicit.append(_col)
        _seen.add(_col)
_remaining = [col for col in df.columns if col not in _seen]
if _unknown_placeholder in _column_order:
    _out_columns = []
    _remaining_inserted = False
    for _col in _column_order:
        if _col == _unknown_placeholder:
            if not _remaining_inserted:
                _out_columns.extend(_remaining)
                _remaining_inserted = True
        elif _col in df.columns and _col not in _out_columns:
            _out_columns.append(_col)
    if not _remaining_inserted:
        _out_columns.extend(_remaining)
else:
    _out_columns = _explicit + _remaining
out_df = df.loc[:, _out_columns].copy()
context['1521:1'] = out_df

################################################################################################################################################################
## Column Resorter # `1522`
# Node state: `EXECUTED`
# Input: [Port 1] 1519:1 from Column Renamer #1519
# Output: [Port 1] 1522:1 to 1523 Concatenate #1523
# https://hub.knime.com/knime/extensions/org.knime.features.base/latest/org.knime.base.node.preproc.columnresorter.ColumnResorterNodeFactory
df = context['1519:1']  # input table
_column_order = ['Country', 'Number approved', 'Number declined', '<any unknown new column>']
_unknown_placeholder = '<any unknown new column>'
_seen = set()
_explicit = []
for _col in _column_order:
    if _col == _unknown_placeholder:
        continue
    if _col in df.columns and _col not in _seen:
        _explicit.append(_col)
        _seen.add(_col)
_remaining = [col for col in df.columns if col not in _seen]
if _unknown_placeholder in _column_order:
    _out_columns = []
    _remaining_inserted = False
    for _col in _column_order:
        if _col == _unknown_placeholder:
            if not _remaining_inserted:
                _out_columns.extend(_remaining)
                _remaining_inserted = True
        elif _col in df.columns and _col not in _out_columns:
            _out_columns.append(_col)
    if not _remaining_inserted:
        _out_columns.extend(_remaining)
else:
    _out_columns = _explicit + _remaining
out_df = df.loc[:, _out_columns].copy()
context['1522:1'] = out_df

################################################################################################################################################################
## String to Number # `1525`
# Node state: `EXECUTED`
# Input: [Port 1] 1518:1 from Column Renamer #1518
# Output: [Port 1] 1525:1 to 1523 Concatenate #1523
# https://hub.knime.com/knime/extensions/org.knime.features.base/latest/org.knime.base.node.preproc.colconvert.stringtonumber2.StringToNumber2NodeFactory
df = context['1518:1']  # input table
out_df = df.copy()
_target_cols = ['Number approved']
_cols = [c for c in _target_cols if c in out_df.columns]
_dec = '.'
_thou = ','
_target = 'Int64'  # 'Float64' or 'Int64'
_raise = False
for _c in _cols:
    _s = out_df[_c].astype('string').str.strip()
    if _thou:
        _s = _s.str.replace(_thou, '', regex=False)
    if _dec and _dec != '.':
        _s = _s.str.replace(_dec, '.', regex=False)
    try:
        _num = pd.to_numeric(_s, errors=('raise' if _raise else 'coerce'))
        if _target == 'Int64':
            if _raise:
                # ensure no fractional part remains for non-NA values
                if (_num.dropna() % 1 != 0).any():
                    raise ValueError(f'Non-integer value encountered in column {_c}')
                out_df[_c] = _num.astype('Int64')
            else:
                # round before casting to nullable Int64; preserves <NA>
                out_df[_c] = _num.round().astype('Int64')
        else:
            out_df[_c] = _num.astype('Float64')
    except Exception:
        if _raise:
            raise
        # fail_on_error == False → leave the original column unchanged
        pass
context['1525:1'] = out_df

################################################################################################################################################################
## Concatenate # `1523`
# Node state: `EXECUTED`
# Input: [Port 2] 1520:1 from Column Resorter #1520; [Port 3] 1521:1 from Column Resorter #1521; [Port 4] 1522:1 from Column Resorter #1522; [Port 1] 1525:1 from String to Number #1525
# Output: [Port 1] 1523:1 to 1524 GroupBy #1524
# https://hub.knime.com/knime/extensions/org.knime.features.base/latest/org.knime.base.node.preproc.append.row.AppendedRowsNodeFactory
dfs = []
dfs.append(context['1525:1'])
dfs.append(context['1520:1'])
dfs.append(context['1521:1'])
dfs.append(context['1522:1'])
out_df = (pd.concat(dfs, axis=0, ignore_index=True, sort=False) if dfs else pd.DataFrame())
context['1523:1'] = out_df

################################################################################################################################################################
## GroupBy # `1524`
# Node state: `EXECUTED`
# Input: [Port 1] 1523:1 from Concatenate #1523
# Output: [Port 1] 1524:1 to 1527 Row Filter #1527
# https://hub.knime.com/knime/extensions/org.knime.features.base/latest/org.knime.base.node.preproc.groupby.GroupByNodeFactory
df = context['1523:1']  # input table
_group_cols = ['Country']
_aggregations = [{'column': 'Number approved', 'method': 'Sum_V2.5.2', 'include_missing': False}, {'column': 'Number declined', 'method': 'Sum_V2.5.2', 'include_missing': False}]
_retain_order = False
_group_cols = [c for c in _group_cols if c in df.columns]

def _gb_method_key(method):
    raw = str(method or '').strip()
    key = raw.lower().replace(' ', '_')
    if '_v' in key:
        key = key.split('_v', 1)[0]
    return key

def _gb_method_name(method):
    key = _gb_method_key(method)
    return {
        'count': 'count',
        'count_unique': 'nunique',
        'unique_count': 'nunique',
        'sum': 'sum',
        'mean': 'mean',
        'average': 'mean',
        'median': 'median',
        'minimum': 'min',
        'min': 'min',
        'maximum': 'max',
        'max': 'max',
        'standard_deviation': 'std',
        'stddev': 'std',
        'variance': 'var',
        'var': 'var',
        'first': 'first',
        'last': 'last',
    }.get(key, key or 'count')

def _gb_output_name(method, column):
    key = _gb_method_key(method)
    method_label = {
        'count': 'Count',
        'count_unique': 'Count unique',
        'unique_count': 'Count unique',
        'sum': 'Sum',
        'mean': 'Mean',
        'average': 'Mean',
        'median': 'Median',
        'minimum': 'Minimum',
        'min': 'Minimum',
        'maximum': 'Maximum',
        'max': 'Maximum',
        'standard_deviation': 'Standard deviation',
        'stddev': 'Standard deviation',
        'variance': 'Variance',
        'var': 'Variance',
        'first': 'First',
        'last': 'Last',
    }.get(key)
    if not method_label:
        method_label = str(method or 'Count').strip() or 'Count'
    return f'{method_label}({column})'

if not _group_cols:
    out_df = df.copy()
elif not _aggregations:
    out_df = (
        df.groupby(_group_cols, dropna=False, sort=not _retain_order)
        .size()
        .reset_index()
        [_group_cols]
    )
else:
    _named_aggs = {}
    for _agg in _aggregations:
        _col = _agg.get('column')
        if _col not in df.columns:
            continue
        _method = _agg.get('method') or 'Count'
        _func = _gb_method_name(_method)
        _out = _gb_output_name(_method, _col)
        if _out in _named_aggs:
            _suffix = 2
            _base = _out
            while _out in _named_aggs:
                _out = f'{_base} #{_suffix}'
                _suffix += 1
        _named_aggs[_out] = (_col, _func)
    if _named_aggs:
        out_df = df.groupby(_group_cols, dropna=False, sort=not _retain_order).agg(**_named_aggs).reset_index()
    else:
        out_df = df.groupby(_group_cols, dropna=False, sort=not _retain_order).size().reset_index()[_group_cols]
context['1524:1'] = out_df

################################################################################################################################################################
## Row Filter # `1527`
# Node state: `EXECUTED`
# Input: [Port 1] 1524:1 from GroupBy #1524
# Output: [Port 1] 1527:1 to 1529 Column Renamer #1529
# https://hub.knime.com/knime/extensions/org.knime.features.base/latest/org.knime.base.node.preproc.filter.row3.RowFilterNodeFactory
df = context['1524:1']  # input table
def _rf_norm_name(s):
    return _re.sub(r'[^a-z0-9]+', '', str(s).lower())
_RF_LCMAP = {c.lower(): c for c in df.columns}
_RF_NORMMAP = {_rf_norm_name(c): c for c in df.columns}

def _rf_resolve(name):
    if name in df.columns:
        return name
    if name is None:
        return None
    c = _RF_LCMAP.get(str(name).lower())
    if c is not None:
        return c
    key = _rf_norm_name(name)
    c = _RF_NORMMAP.get(key)
    if c is not None:
        return c
    # Heuristic aliases for common aggregate column names
    if key in {'occurrencecount','count','rowcount'}:
        cand = [col for col in df.columns if 'count' in _rf_norm_name(col)]
        if len(cand) == 1:
            return cand[0]
    return None

def _rf_to_num(val):
    s = pd.Series([val])
    v = pd.to_numeric(s, errors='coerce').iloc[0]
    return v

mask = pd.Series(True, index=df.index)
_col0 = _rf_resolve('Country')
if _col0 is None:
    _c0 = pd.Series(True, index=df.index)  # missing column → neutral
else:
    _s0 = df[_col0]
    _vals = ['Total']
    _vals_num = [_rf_to_num(v) for v in _vals]
    _all_num = all(pd.notna(x) for x in _vals_num)
    _s_num = pd.to_numeric(_s0, errors='coerce')
    _is_numlike = (pd.api.types.is_numeric_dtype(_s_num) or pd.api.types.is_bool_dtype(_s_num))
    if _all_num and _is_numlike:
        _c0 = (_s_num != _vals_num[0] if _vals_num else float('nan'))
    else:
        _c0 = (_s0.astype('string') != str('Total')).fillna(False)
mask = (mask & _c0)
_invert = False
final_mask = (~mask) if _invert else mask
out_df = df[final_mask].copy()
context['1527:1'] = out_df

################################################################################################################################################################
## Column Renamer # `1529`
# Node state: `EXECUTED`
# Input: [Port 1] 1527:1 from Row Filter #1527
# Output: [Port 1] 1529:1 to 1530 Math Formula #1530
# comments: 4 years
# https://hub.knime.com/knime/extensions/org.knime.features.base/latest/org.knime.base.node.preproc.column.renamer.ColumnRenamerNodeFactory
df = context['1527:1']  # input table
_pairs = [('Sum(Number declined)', 'Number declined'), ('Sum(Number approved)', 'Number approved')]
out_df = df.copy()
# Filter to pairs where the source column exists
present = [(o, n) for (o, n) in _pairs if o in out_df.columns]
if not present:
    final_map = {}
else:
    # Build a collision-safe mapping
    existing = set(out_df.columns)
    final_map = {}
    for old, new in present:
        # If renaming to the same name, keep it (no-op)
        tgt = new
        if tgt != old:
            if tgt in existing and tgt != old:
                base = tgt
                k = 1
                while f"{base}_{k}" in existing:
                    k += 1
                tgt = f"{base}_{k}"
            # update sets for subsequent checks
            existing.discard(old)
            existing.add(tgt)
        final_map[old] = tgt

# Apply rename if any
if final_map:
    out_df = out_df.rename(columns=final_map)
context['1529:1'] = out_df

################################################################################################################################################################
## Math Formula # `1530`
# Node state: `EXECUTED`
# Input: [Port 1] 1529:1 from Column Renamer #1529
# Output: [Port 1] 1530:1 to 1531 Math Formula #1531
# https://hub.knime.com/knime/extensions/org.knime.features.ext.jep/latest/org.knime.ext.jep.JEPNodeFactory
df = context['1529:1']  # input table
out_df = df.copy()
_expr = "df['Number approved']+df['Number declined']"  # translated from JEP
# Evaluate the expression in a restricted namespace
_ns = {'np': np, 'pd': pd, 'df': df}
_res = eval(_expr, {'__builtins__': {}}, _ns)
_res = pd.to_numeric(_res, errors='coerce').round().astype('Int64')
_target_col = 'Total applications'
out_df[_target_col] = _res
context['1530:1'] = out_df

################################################################################################################################################################
## Math Formula # `1531`
# Node state: `EXECUTED`
# Input: [Port 1] 1530:1 from Math Formula #1530
# Output: [Port 1] 1531:1 to 1536 Math Formula #1536
# https://hub.knime.com/knime/extensions/org.knime.features.ext.jep/latest/org.knime.ext.jep.JEPNodeFactory
df = context['1530:1']  # input table
out_df = df.copy()
_expr = "df['Number approved']/df['Total applications']"  # translated from JEP
# Evaluate the expression in a restricted namespace
_ns = {'np': np, 'pd': pd, 'df': df}
_res = eval(_expr, {'__builtins__': {}}, _ns)
_target_col = 'Approval rate'
out_df[_target_col] = _res
context['1531:1'] = out_df

################################################################################################################################################################
## Math Formula # `1536`
# Node state: `EXECUTED`
# Input: [Port 1] 1531:1 from Math Formula #1531
# Output: [Port 1] 1536:1 to 1585 CSV Writer #1585
# https://hub.knime.com/knime/extensions/org.knime.features.ext.jep/latest/org.knime.ext.jep.JEPNodeFactory
df = context['1531:1']  # input table
out_df = df.copy()
_expr = "np.log10(df['Total applications'])"  # translated from JEP
# Evaluate the expression in a restricted namespace
_ns = {'np': np, 'pd': pd, 'df': df}
_res = eval(_expr, {'__builtins__': {}}, _ns)
_target_col = 'Applications_log10'
out_df[_target_col] = _res
context['1536:1'] = out_df

################################################################################################################################################################
## CSV Writer # `1585`
# Node state: `CONFIGURED`
# Input: [Port 1] 1536:1 from Math Formula #1536
# comments: INZ.csv
# https://hub.knime.com/knime/extensions/org.knime.features.base/latest/org.knime.base.node.io.filehandling.csv.writer.CSVWriter2NodeFactory
df = context['1536:1']
out_path = Path(r"data/prepared/inz_student_visa_decisions_2022-2025.csv")
df = df.copy()
for _col in df.select_dtypes(include=['datetime', 'datetimetz']).columns:
    df[_col] = df[_col].dt.strftime('%Y-%m-%dT%H:%M')
def _k2p_format_timedelta(_value):
    if pd.isna(_value):
        return pd.NA
    _total_minutes = int(pd.Timedelta(_value).total_seconds() // 60)
    if _total_minutes == 0:
        return 'PT0S'
    _sign = -1 if _total_minutes < 0 else 1
    _hours, _minutes = divmod(abs(_total_minutes), 60)
    if _sign < 0:
        if _hours and _minutes:
            return f'PT-{_hours}H-{_minutes}M'
        if _hours:
            return f'PT-{_hours}H'
        return f'PT-{_minutes}M'
    if _hours and _minutes:
        return f'PT{_hours}H{_minutes}M'
    if _hours:
        return f'PT{_hours}H'
    return f'PT{_minutes}M'
for _col in df.select_dtypes(include=['timedelta']).columns:
    df[_col] = df[_col].map(_k2p_format_timedelta)
for _col in df.select_dtypes(include=['float']).columns:
    _series = df[_col].dropna()
    if not _series.empty and ((_series % 1) == 0).all():
        df[_col] = df[_col].astype('Int64')
_k2p_missing_sentinel = '__K2P_MISSING_FIELD_9b1f6f7c__'
df = df.astype('object').mask(df.isna(), _k2p_missing_sentinel)
df.to_csv(out_path, sep=',', quotechar='"', header=True, encoding='UTF-8', na_rep='', index=False, quoting=csv.QUOTE_NONNUMERIC)
_k2p_csv_text = out_path.read_text(encoding='UTF-8')
_k2p_csv_text = _k2p_csv_text.replace('"' + _k2p_missing_sentinel + '"', '')
out_path.write_text(_k2p_csv_text, encoding='UTF-8')
